# Generated by Django 2.0.7 on 2018-07-31 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portal', '0002_auto_20180731_1118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('slug', models.SlugField(unique=True)),
                ('quantity', models.IntegerField(default=1)),
                ('prince', models.DecimalField(decimal_places=2, max_digits=8)),
                ('short_description', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20)),
                ('Categories', models.ManyToManyField(blank=True, related_name='categories', to='portal.Category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
